version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    build:
      context: ./docker/db
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    
  web:
    build:
      context: .
    ports:
      - 8000:3000
    expose:
      - 3000
    volumes:
      - ./api:/root/api
    env_file:
      - ./.env
    depends_on:
      - db

  # All of the below config is for a mongo connection
  # # mongo database instance
  # mongo:
  #   image: mongo:4
  #   restart: always
  #   env_file:
  #     - ./.env